Dependencies update
datatags/UltraCosmetics pull request #125
Opened 2023-07-30 19:37 UTC by BySwiizen

Only **[WorldGuard](https://dev.bukkit.org/projects/worldguard)** is not updated for compatibility reasons.

2023-07-30 21:10 UTC, datatags requested changes

2023-07-30 21:10 UTC, datatags commented on core/build.gradle
> +    implementation 'com.zaxxer:HikariCP:5.0.1'
```suggestion
    // Last version to support Java 8
    implementation 'com.zaxxer:HikariCP:4.0.3'
```
From the build output it seems this version of Hikari is needed

2023-07-30 22:24 UTC, BySwiizen commented
There are packages not found @datatags.

2023-07-31 00:42 UTC, datatags commented
Hmm, looks like the Treasury API changed a bunch so I'll go ahead and merge it so I can play around with it. I'm glad they changed it, it was hard to use before 😂

2023-07-31 00:42 UTC, datatags approved these changes

2023-07-31 00:42 UTC, merged